---
collections:
  - name: ansible.netcommon
    version: 6.1.0
    source: https://galaxy.ansible.com
  - name: arista.avd
    version: 4.6.0
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 3.8.1
    source: https://galaxy.ansible.com
  - name: community.general
    version: 8.6.4
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com
  - name: vyos.vyos
    version: 4.1.0
    source: https://galaxy.ansible.com
