---
collections:
  - name: ansible.netcommon
    version: 8.2.0
  - name: ansible.posix
    version: 2.1.0
  - name: arista.avd
    version: 5.7.2
  - name: cisco.ios
    version: 11.2.0
  - name: community.docker
    version: 5.0.2
  - name: community.general
    version: 12.0.1
  - name: vyos.vyos
    version: 6.0.0
