---
collections:
  - name: ansible.netcommon
    version: 7.2.0
    source: https://galaxy.ansible.com
  - name: arista.avd
    version: 5.6.0
    source: https://galaxy.ansible.com
  - name: vyos.vyos
    version: 5.0.0
    source: https://galaxy.ansible.com
