---
collections:
  - name: ansible.netcommon
    version: 8.1.0
  - name: ansible.posix
    version: 2.1.0
  - name: arista.avd
    version: 5.7.1
  - name: cisco.ios
    version: 11.1.1
  - name: community.docker
    version: 4.8.2
  - name: community.general
    version: 12.0.0
  - name: vyos.vyos
    version: 6.0.0
