---
collections:
  - name: ansible.netcommon
    version: 7.1.0
    source: https://galaxy.ansible.com
  - name: arista.avd
    version: 4.6.0
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 3.12.1
    source: https://galaxy.ansible.com
  - name: community.general
    version: 10.2.0
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com
  - name: vyos.vyos
    version: 5.0.0
    source: https://galaxy.ansible.com
