---
collections:
  - name: ansible.netcommon
    version: 7.2.0
    source: https://galaxy.ansible.com
  - name: arista.avd
    version: 5.2.3
    source: https://galaxy.ansible.com
  - name: vyos.vyos
    version: 6.0.0
    source: https://galaxy.ansible.com
